name: vertx-json-schema (5.x)
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  Debug:
    name: Debug env issue
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: master
      - name: Install JDK
        uses: actions/setup-java@v2
        with:
          java-version: 11
          distribution: temurin
      - name: Get project version
        run: echo "PROJECT_VERSION=$(mvn org.apache.maven.plugins:maven-help-plugin:evaluate -Dexpression=project.version -q -DforceStdout | grep -v '\[')" >> $GITHUB_ENV
